### ISSUE TITLE
Change Main Character

### ISSUE THREAD

**Issue by mindcloud69** [jaygumji/ArcemiPathfinderKingmakerTools#6]
So when using tools like toybox for gestalt characters you can mess up who the main character is. You cahn change this by putting the guid of the main character in the variable m_MainCharacter in the player.json having this in you editor would make fixing this really easy.

**Comment by jaygumji** [comment]
It should be easy to implement, I'll have it with the next version

**Comment by mindcloud69** [comment]
Thank you

**Comment by jaygumji** [comment]
This has been implemented in version 1.1.1

**Comment by mindcloud69** [comment]
I appreciate your hard work. Thanks again!
