### ISSUE TITLE
Snap feedback and suggestion

### ISSUE THREAD

**Issue by lynxlynxlynx** [jaygumji/ArcemiPathfinderKingmakerTools#7]
Hey, used the editor for the second time today and it's clear it improved in the meanwhile.

I suggest you mention in the linux docs that to run it: `sudo snap run arcemi-pathfinder-save-game-editor`
And that it's important to run it with sudo if you installed it that way, to get access to all disks and folders. Otherwise it's a PITA.

**Comment by jaygumji** [comment]
Thank you for the feedback, good to hear it works well otherwise!

I've updated the mod details with the info in the installation info.
